version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/calorietracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&connectTimeout=10000
      SPRING_DATASOURCE_USERNAME: calorieuser
      SPRING_DATASOURCE_PASSWORD: caloriepassword

  mysql:
    image: mysql:8.0.31
    # platform: linux/arm64/v8
    container_name: mysql
    environment:
      MYSQL_DATABASE: calorietracker
      MYSQL_USER: calorieuser
      MYSQL_PASSWORD: caloriepassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
